spring.application.name=Injection-Depandcy
spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5434}/${POSTGRES_DB:springboot}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
